language: java
jdk:
  - openjdk8

branches:
  only:
    - develop

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script:
    "./gradlew bootJar -p matcherloper-web clean",
      "./gradlew bootJar -p matcherloper-web"

before_deploy:
  - zip -r matcherloper *
  - mkdir -p deploy
  - mv matcherloper.zip deploy/matcherloper.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 ::설정된 값
    bucket: matcherloper-deploy
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: MatcherLoper/MatcherLoper_Server
      branch: develop

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: matcherloper-deploy # S3 버킷
    key: matcherloper.zip # S3 버킷에 저장된 springboot-webservice.zip 파일을 EC2로 배포
    bundle_type: zip
    application: matcherloper # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: matcherloper-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: MatcherLoper/MatcherLoper_Server
      branch: develop

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - bkh115819@gmail.com
      - jinmin2216@naver.com
