language: java
jdk:
  - openjdk8

branches:
  only:
    - infla/matcherloper-39

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew bootJar -p matcherloper-web clean"

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 ::설정된 값
    bucket: matcherloper-deploy # 6-3-3에서 생성한 S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: https://github.com/MatcherLoper/MatcherLoper_Server/tree/infla/matcherloper-39 #Github 주소
      branch: infla/matcherloper-39

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - bkh115819@gmail.com
      - jinmin2216@naver.com